# Generated by Django 4.1.2 on 2022-10-18 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homelib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(db_index=True, max_length=50, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_genre', models.CharField(db_index=True, max_length=50, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_language', models.CharField(db_index=True, max_length=50, verbose_name='Язык')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='book_image',
            field=models.ImageField(blank=True, upload_to='book_images/', verbose_name='Изображения книги'),
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='homelib.authors', verbose_name='Авторы'),
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='homelib.genres', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='homelib.languages', verbose_name='Языки'),
        ),
    ]
