# Generated by Django 4.1.2 on 2022-10-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelib', '0002_authors_genres_languages_books_book_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ['name_genre'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={'verbose_name': 'Язык', 'verbose_name_plural': 'Языки'},
        ),
        migrations.AddField(
            model_name='authors',
            name='surname_author',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Фамилия Автора'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='name_author',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Имя автора'),
        ),
    ]
