# Generated by Django 4.1.2 on 2022-10-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelib', '0003_alter_authors_options_alter_books_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='surname_author',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Фамилия Автора'),
        ),
    ]
