# Generated by Django 4.1.2 on 2022-10-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelib', '0005_alter_authors_options_alter_books_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='first_name_author',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_name_author',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Фамилия автора'),
        ),
    ]
