# Generated by Django 4.1.2 on 2022-10-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelib', '0010_alter_books_options_bookfeedbacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookfeedbacks',
            name='book_feedback_date_upd',
        ),
    ]
