# Generated by Django 4.1.2 on 2022-10-29 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homelib', '0014_cities_libraries_libbooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraries',
            name='city',
        ),
        migrations.AddField(
            model_name='libraries',
            name='library_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='homelib.cities', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='libraries',
            name='library_contacts',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Контакты библиотеки'),
        ),
        migrations.AlterField(
            model_name='libraries',
            name='library_description',
            field=models.CharField(default=' ', max_length=300, verbose_name='Описание библиотеки'),
        ),
    ]
