# Generated by Django 4.1.2 on 2022-10-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelib', '0018_alter_libraries_library_reader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookfeedbacks',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'ordering': ['city_name'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='libbooks',
            options={'verbose_name': 'Книга библиотеки', 'verbose_name_plural': 'Книги библиотеки'},
        ),
        migrations.AlterModelOptions(
            name='libraries',
            options={'ordering': ['library_name'], 'verbose_name': 'Домащняя библиотека', 'verbose_name_plural': 'Домашние библиотеки'},
        ),
        migrations.RemoveField(
            model_name='libraries',
            name='library_reader',
        ),
    ]
