# Generated by Django 4.1.2 on 2022-10-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelib', '0020_rename_definition_books_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='description',
            new_name='definition',
        ),
    ]
